name: Run tests

on:
  workflow_dispatch:
  #push:
  #  branches: ['*']
    
jobs:
  run_matrix:
    strategy:
      fail-fast: false
      matrix:
        script: 
          - account
          - ai
          - backtest_charts
          - backtest_insights
          - backtest_orders
          - backtests
          - compile
          - files
          - lean_versions
          - live
          - live_charts
          - live_commands
          - live_insights
          - live_logs
          - live_orders
          - mcp_server_version
          - object_store
          - optimization
          - project
          - project_collaboration
          - project_nodes

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip 
          pip install mcp[cli]==1.10.1, pytest-asyncio==1.0.0, requests

      - name: Free space
        run: df -h && rm -rf /opt/hostedtoolcache* && df -h

      - name: Run test_${{ matrix.script }}.py
        run: |-
          cd tests; pytest test_${{ matrix.script }}.py
        env:
          QUANTCONNECT_USER_ID: ${{ secrets.QUANTCONNECT_USER_ID }}
          QUANTCONNECT_API_TOKEN: ${{ secrets.QUANTCONNECT_API_TOKEN }}
          QUANTCONNECT_COLLABORATOR_ID: ${{ secrets.QUANTCONNECT_COLLABORATOR_ID }}
          QUANTCONNECT_ORGANIZATION_ID: ${{ secrets.QUANTCONNECT_ORGANIZATION_ID }}
